#!/usr/bin/env php
<?php

require_once __DIR__ . '/Catalog.php';

if (php_sapi_name() !== 'cli') {
    exit;
}

$app = new Catalog();

$action = $argv[1] ?? '';
$context = $argv[2] ?? '';

switch($action){
    case 'all':
        echo 'Attempting to find all records...' . PHP_EOL. PHP_EOL;
        $results = $app->getAllRecords();
        if($results){
            foreach ($results as $type => $types) {
                echo 'Printing records for type: ' . $type . PHP_EOL;
                foreach ($types as $record) {
                    printRecord($record);
                }
            }
        }
        break;
    case 'find':
        if(!empty($context)){
            echo 'Attempting to find record with ISBN: '.$context . PHP_EOL. PHP_EOL;
            $record = $app->getRecord($context);
            if($record){
                printRecord($record);
            } else {
                echo 'Record not found.' . PHP_EOL;
            }
        } else {
            echo 'Please provide an id to search'.PHP_EOL;
        }
        break;
    case 'add':
            $type = readline('Type: ');
            $data['isbn'] = readline('ISBN: ');
            $data['title'] = readline('Title: ');
            $data['author'] = readline('Author: ');
            while(($name = readline('Additional Data Name:')) !== ''){
                $data[$name] = readline($name.' Value: ');
            }
            $app->addRecord($type, $data);
        break;
    case 'help':
    default:
        if($action != 'help'){
            echo "Unknown action.PHP_EOL";
        }
        echo "Usage: PHP_EOL\thelp - this helpPHP_EOL\tall - list all recordsPHP_EOL\tfind <isbn> - find a record by idPHP_EOL\tadd - add a recordPHP_EOL";
        break;
}

function printRecord($record){
    echo 'Title: '.$record->getTitle() . PHP_EOL;
    echo 'Author: '.$record->getAuthor() . PHP_EOL;
    echo 'Created Date: '.$record->getCreatedDate()->format('m/d/Y') . PHP_EOL;
    echo 'ISBN: '.$record->getIsbn() . PHP_EOL;
    echo PHP_EOL;
}